services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    networks:
      - inception-network
    ports:
      - "443:443"
    restart: no
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./mariadb
    networks:
      - inception-network
    volumes:
      - /home/pmelo-ca/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: no
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./wordpress
    networks:
      - inception-network
    volumes:
      - /home/pmelo-ca/data:/var/wordpress
    ports:
      - "9000:9000"
    restart: no
networks:
  inception-network:
