services:
  nginx:
    container_name: nginx-container
    image: nginx-image
    build: ./nginx
    networks:
      - inception-network
    volumes:
      - wordpress-data:/srv/www/wordpress
    ports:
      - "443:443"
    restart: on-failure
    depends_on:
      - mariadb
      - wordpress
  mariadb:
    container_name: mariadb-container
    image: mariadb-image
    build: ./mariadb
    networks:
      - inception-network
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: on-failure
  wordpress:
    container_name: wordpress-container
    image: wordpress-image
    build: ./wordpress
    networks:
      - inception-network
    volumes:
      - wordpress-data:/srv/www/wordpress
    ports:
      - "9000:9000"
    environment:
      - WORDPRESS_MYSQL_HOST=${MYSQL_HOST}
      - WORPRESS_MYSQL_PORT=${MYSQL_PORT}
      - WORDPRESS_MYSQL_USER=${MYSQL_USER}
      - WORDPRESS_MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: on-failure
    depends_on:
      - mariadb

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pmelo-ca/data/wordpress
  mariadb-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pmelo-ca/data/mariadb