services:
  nginx:
    container_name: nginx
    image: nginx-image
    build: ./nginx
    networks:
      - inception-network
    volumes:
      - wordpress-data:/srv/www/wordpress
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mariadb
      - wordpress
  mariadb:
    container_name: mariadb
    image: mariadb-image
    build: ./mariadb
    networks:
      inception-network:
        ipv4_address: 172.18.0.2
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress-image
    build: ./wordpress
    networks:
      - inception-network
    volumes:
      - wordpress-data:/srv/www/wordpress
    environment:
      - WORDPRESS_MYSQL_HOST=${MYSQL_HOST}
      - WORDPRESS_MYSQL_USER=${MYSQL_USER}
      - WORDPRESS_MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: on-failure
    depends_on:
      - mariadb

  # adminer:
  #   container_name: adminer
  #   image: adminer-image
  #   build: ./bonus/adminer
  #   networks:
  #     - inception-network
  #   environment:
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_HOST=${MYSQL_HOST}
  #     - MYSQL_PORT=${MYSQL_PORT}
  #   restart: on-failure
  #   depends_on:
  #     - mariadb

networks:
  inception-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pmelo-ca/data/wordpress
  mariadb-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pmelo-ca/data/mariadb